[character]
success_symbol = '[❯](bold green)'
error_symbol = '[✗](bold red)'

# Shows kubernetes context and namespace
# [kubernetes]
# format = 'via [󱃾 $context\($namespace\)](bold purple) '
# disabled = false

[directory]
truncation_symbol = '…/'

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
